import './globals.css'

import Header from '../app/Components/Header';
import Footer from '../app/Components/Footer';

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Cookie Stand Admin',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <Header/>
        {children}
        
        <Footer/>
        
        </body>
    </html>
  )
}